name: aicontentworld
favicon: null
layout_spectrum: 0.8533495352603495
typography_spectrum: 0.9940313033293933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cbc395'
    - '#404040'
    - '#ba2026'
    - '#4f94a3'
  brandStrength: 1
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 1
purpose: []
